create table users (
    id bigint generated by default as identity primary key,
    username varchar(100) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    role varchar(30) not null default 'USER',
    enabled boolean not null default true,
    account_non_locked boolean not null default true,
    status varchar(30) not null default 'ACTIVE',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    deleted_at timestamp,
    constraint uk_users_username unique (username),
    constraint uk_users_email unique (email),
    constraint ck_users_role check (role in ('USER', 'ADMIN')),
    constraint ck_users_status check (status in ('ACTIVE', 'DELETED'))
);

create table file_metadata (
    id bigint generated by default as identity primary key,
    owner_user_id bigint not null,
    title varchar(150) not null,
    description varchar(1000),
    category varchar(100) not null,
    original_filename varchar(255) not null,
    stored_filename varchar(255) not null,
    content_type varchar(120) not null,
    extension varchar(20) not null,
    size_bytes bigint not null,
    sha256_checksum varchar(64) not null,
    storage_path varchar(1000) not null,
    status varchar(30) not null default 'ACTIVE',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    deleted_at timestamp,
    constraint fk_file_metadata_owner foreign key (owner_user_id) references users (id),
    constraint uk_file_metadata_stored_filename unique (stored_filename),
    constraint ck_file_metadata_size_positive check (size_bytes > 0),
    constraint ck_file_metadata_status check (status in ('ACTIVE', 'DELETED'))
);

create table file_download_audits (
    id bigint generated by default as identity primary key,
    file_id bigint,
    downloaded_by_user_id bigint not null,
    downloaded_at timestamp not null default current_timestamp,
    constraint fk_file_download_audits_file foreign key (file_id) references file_metadata (id) on delete set null,
    constraint fk_file_download_audits_user foreign key (downloaded_by_user_id) references users (id)
);

create index idx_users_enabled on users (enabled);
create index idx_users_role on users (role);
create index idx_users_status on users (status);
create index idx_file_metadata_owner_status_created_at on file_metadata (owner_user_id, status, created_at);
create index idx_file_metadata_checksum on file_metadata (sha256_checksum);
create index idx_file_download_audits_file_id on file_download_audits (file_id);
create index idx_file_download_audits_user_downloaded_at on file_download_audits (downloaded_by_user_id, downloaded_at);
